{% set name = "fmrib-unpack" %}
{% set version = "1.4.5" %}
{% set sha256 = "10fe2efcbb3c40343ffc600cc0e95a63cbfea44377e0cf89cccc16709af9e0db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
   - funpack      = funpack.main:main
   - funpack_demo = funpack.scripts.demo:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - h5py
    - numpy
    - pandas
    - pyparsing
    - six
    - pytables
    - jupyter
    - notebook
    - pygments

test:
  requires:
    - pip
    - coverage
    - pytest
    - pytest-cov
    - jinja2
    - notebook
    - jupyter
    - pygments

  commands:
    # bash_kernel is not available on
    # conda, but is imported by the
    # funpack.scripts.demo module
    - pip install bash_kernel
    - funpack -V
    - funpack_demo -h
    - pytest -v --cov=funpack --pyargs funpack.tests -k "not (lowMemory or HDF or test_demo)"


about:
  home: https://git.fmrib.ox.ac.uk/fsl/funpack/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The FMRIB UKBioBank Normalisation, Parsing And Cleaning Kit'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/funpack/

extra:
  recipe-maintainers:
    - pauldmccarthy
