{% set name = "fmrib-unpack" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c56095731d754ff980df0efc46d5a5041762605886be5700783837bb78faf752

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fmrib_unpack      = funpack.main:main
    - fmrib_unpack_demo = funpack.scripts.demo:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fmrib-unpack-fmrib-config
    - h5py
    - numpy
    - pandas >=0.24
    - pyparsing
    - pytables
    - jupyter
    - notebook
    - pygments
    - threadpoolctl
    - typing-extensions
    - bash_kernel

test:
  requires:
    - pip
    - coverage
    - pytest
    - pytest-cov
    - jinja2

  commands:
    - fmrib_unpack -V
    - fmrib_unpack_demo -h

# check test markers
    - pytest -v --cov=funpack --pyargs funpack.tests -k "not (lowMemory or HDF or test_demo)"


about:
  home: https://git.fmrib.ox.ac.uk/fsl/funpack/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FMRIB UKBioBank Normalisation, Parsing And Cleaning Kit
  dev_url: https://git.fmrib.ox.ac.uk/fsl/funpack/

extra:
  recipe-maintainers:
    - pauldmccarthy
