{% set name = "fmrib-unpack" %}
{% set version = "2.5.1" %}
{% set sha256 = "20f5d1a73b1404e0d7e7d0c5b082cec1bf5feca5aa07bb5d656a5fd5b4bb3c97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - funpack      = funpack.main:main
    - funpack_demo = funpack.scripts.demo:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - h5py
    - numpy
    - pandas >=0.24
    - pyparsing
    - six
    - pytables
    - jupyter
    - notebook
    - pygments
    - threadpoolctl
    - bash_kernel

test:
  requires:
    - pip
    - coverage
    - pytest
    - pytest-cov
    - jinja2

  commands:
    - funpack -V
    - funpack_demo -h

# check test markers
    - pytest -v --cov=funpack --pyargs funpack.tests -k "not (lowMemory or HDF or test_demo)"


about:
  home: https://git.fmrib.ox.ac.uk/fsl/funpack/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FMRIB UKBioBank Normalisation, Parsing And Cleaning Kit
  dev_url: https://git.fmrib.ox.ac.uk/fsl/funpack/

extra:
  recipe-maintainers:
    - pauldmccarthy
