travis:
  secure:
    BINSTAR_TOKEN: z1+cLwKDoo34I5eFC9tJn82Vb3YmrdYDVEca8VdaGlIRv+WdJvL2Ls753yI9PFLwiFoLqJVaH8oQUgzWxrDV1shqeHmPsa7kshmjr9g6f0FgEQbQKJbhQrFRn8vbxHeberLfjF+GJlQhS6W3XHxj3n4r55TI5aPfMV4mCVinkN7kIQtPJFI5U8xEzwufFCSpSSoxkm2AidJ4RQnXejgcyFT7eB+YaN81gIRAFhxof0oCWI5NIkrzgZhlMwSfgBoyytNIkaGJLk4GUtQE5nNGc4g6HtzUs8HDXLNII1YXQLOjI8Uvn/CHS1phskLMfRyjGYj4vnluV+4NjdjY+s1BGxibuFWy8mB9awTwt46ZTcE/1//JGuqVSapSl7G/yiJNfczhzJGLC7d71+ucXBIouT46bVl+SySBgxlUW5IpKz/rTZuCdhOuFSoHms2IbqAFXxigRsVkEdjAUnuv6AFjdcSPwLWQglztZNsuEAEVCyPuh9O/nnwYsrGP3KjntPFVNB+vos/AoOjGWJaqyPzKKMVeGf1zPaVXJBmVOs5htV9NtGjHPcVHeCsYtkgokLc6FQ/6ZUDBGkNqQfhRIf4rUCsxJg8XwlHGKveT9x/+PvvYza71tuFJBu3Y9L/gM+uHgjTfrrguVLPP1+msa1h/8d8KD2WRBnx8l132LJuqeV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
