travis:
  secure:
    BINSTAR_TOKEN: rHm/aJTA7zkiunesTWnXwx2Xo+nd2FLwwviVB9ArCvbMRrf1bJmRiwiPXYGcGSugWpyEBtab6Rym8c/Gudu0SMffeUdVqdVde2wktypN/gRUte2GZ3NURC6yR6T1tzdNMixgCzCG22+BwdjUVYqhcY4q85uUa83IuRNoaINaO9vRQdiN7DD65VbIgfChxY2uSd1LYjQnrRUV19qNkDoI4fKcmLT/ZQNOKdR/BLBJVuxkDcbtLK8m6cjFIrNiiSdDA4fUg8hInoTGBKn57pqm71NDia47vUMxGQPAta9JLVgazHu/yO6dT9Uhpzu2QXnjk66DbFKSJ/OwsOPO2dkZ+fY96BP84KJeLKmIgBuhBoeVEbKhD1WRUcKPpKYBwvuFQNstZR3CE7LO8q3Bnm6zSqIMlpMTBB46Ov8AzURM1p1kfnLopZCtLWWltnOLWUrPrz5QRsOBaXtlofIeQCHYsHpK12Y5lYRt4JCKDl9jgdfo3kEKAHSXMS14qvLo1YG6Tpv9jWd6vAF/QE9WSjFjhuk2OisTFz0+5l6expNI8Irs97r8YdW6V9yHTQAlvjirxu7LLESYgSVsQQe7lQzMZtGG3rGVfyTTPDgQt8K7aiRC+nfEi/FaL4LI0eidnzqdcVGTNO+E9t3fDg0NS8XvM8gHGLDv5YvRe3R/LxFGZsE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
